Added chapter about new Reports UI
plentymarkets/plenty-manual-docs pull request #1055
Opened 2022-09-01 11:43 UTC by snawratil

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* erhältst du einen Überblick über Auftragsberichte von Amazon. Hier kannst du sehen, welche Berichte bereits verarbeitet wurden und we
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* erhältst du einen Überblick über Auftragsberichte von Amazon. Hier kannst du sehen, welche Berichte bereits verarbeitet wurden und we
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Du kannst die Amazon-Berichte auch zurücksetzen oder überspringen. So kannst du festlegen, welche Berichte zuerst verarbeitet werden sollen oder auch die Auslastung deines Systems reduzieren, indem d
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +[cols="1,3a"]
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceNumberOfCommas] Schreibe den Satz so um, dass du weniger Kommas benötigst. Vermeide dabei Satzeinschübe und mehrere Nebensätze. Wenn der Bezug erhalten bleibt, kannst du einen Nebensatz an das Satzende stellen. Aufzählungen ab vier Elementen sollten in einer Liste dargestellt werden.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Der Berichtstyp. Eine Übersicht darüber, welche Berichtstypen es bei Amazon-Berichten gibt, findest du <<#amazon-berichtstypen, hier>>.
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Der Berichtstyp. Eine Übersicht darüber, welche Berichtstypen es bei Amazon-Berichten gibt, findest du <<#amazon-berichtstypen, hier>>.
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceEndPunctuation] Jeder Satz muss mit einem Punkt, Doppelpunkt oder Fragezeichen abgeschlossen werden. Vermeide es, Sätze z.B. durch eine Liste zu unterbrechen. Dadurch werden Sinnzusammenhänge deutlich.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| *_Hinweis:_* Einige Berichtstypen können nicht zurückgesetzt oder übersprungen werden. +
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ImpreciseStatements] Vermeide ungenaue Aussagen wie 'Einige', damit es keine Unklarheiten oder Missverständnisse gibt.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +* *Bericht zurücksetzen* (material:history[]): Der Bericht wird zurückgesetzt. Wenn du einen Bericht zurücksetzt, wird der Bericht neu verarbeitet. Das kann zum Beispiel hilfreich sein, wenn der Beri
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +* *Bericht zurücksetzen* (material:history[]): Der Bericht wird zurückgesetzt. Wenn du einen Bericht zurücksetzt, wird der Bericht neu verarbeitet. Das kann zum Beispiel hilfreich sein, wenn der Beri
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Auftragsberichte werden dann unter Umständen erst später
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.CompoundNumbers] Verwende in Komposita Ziffern statt Zahlwörter, um eine einheitliche Schreibweise sicherzustellen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Auftragsberichte werden dann unter Umständen erst später
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Auftragsberichte werden dann unter Umständen erst später
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Auftragsberichte werden dann unter Umständen erst später
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsExceptions] Kennzeichne Ausnahmen explizit und vermeide Wörter wie 'unter Umständen', damit die Aussage eindeutig ist.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Auftragsberichte werden dann unter Umständen erst später
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsTemporal] Vermeide Wörter, die die zeitliche Abfolge beschreiben, wie 'erst'. Dadurch wird die Verständlichkeit erhöht.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Berichte zu überspringen kann sinnvoll sein, wenn du die Auslastung deines Systems reduzieren willst. Außerdem kannst du so bestimmen, welche Berichte als nächstes verarbeitet werden sollen, denn wen
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Berichte zu überspringen kann sinnvoll sein, wenn du die Auslastung deines Systems reduzieren willst. Außerdem kannst du so bestimmen, welche Berichte als nächstes verarbeitet werden sollen, denn wen
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| * Korrigieren und Importieren externer Rechnungen und Gutschriften auf Basis von VCS/VCS Amazon
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidConnectingCharacters] Vermeide Sonderzeichen in Benennungen, um eine einheitliche Schreibweise sicherzustellen und die Lesbarkeit zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +*_Tipp:_* Du kannst die gewählten Filter auch *zurücksetzen* (material:refresh[]). Dann werden wieder alle Amazon-Berichte angezeigt.
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Aktualisierung von* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedu
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidAllCapsWords] Vermeide Wörter in Großbuchstaben, außer es handelt sich dabei um ein Akronym oder einen Eigennamen. Wenn du ein Signalwort (z.B. "Hinweis") besonders kennzeichnen möchtest, verwende stattdessen eine Kombination aus Fettdruck und Kursivdruck.

2022-09-01 11:44 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Datum im Format *D.M.YYYY* eingeben oder über den Kalender (material:today[]) wählen. In der Zeile *Uhrzeit Aktualisierung bis* kannst du zusätzlich eine Uhrzeit eingeben oder über (material:schedu
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidAllCapsWords] Vermeide Wörter in Großbuchstaben, außer es handelt sich dabei um ein Akronym oder einen Eigennamen. Wenn du ein Signalwort (z.B. "Hinweis") besonders kennzeichnen möchtest, verwende stattdessen eine Kombination aus Fettdruck und Kursivdruck.

2022-09-02 06:41 UTC, jschaakplenty requested changes

2022-09-02 06:41 UTC, jschaakplenty commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Verkäufer-ID aus der Dropdown-Liste wählen, um nur Berichte mit dieser Verkäufer-ID anzuzeigen.
Hinweis: Die Verkäufer-ID ist Pflicht, diese muss gewählt werden. Ist keine gewählt, werden keine Berichte angezeigt.

2022-09-02 08:21 UTC, snawratil commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +| Verkäufer-ID aus der Dropdown-Liste wählen, um nur Berichte mit dieser Verkäufer-ID anzuzeigen.
done

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* erhältst du einen Überblick über den Verarbeitungsstand deiner Amazon-Berichte. Hier kannst du sehen, welche Berichte bereits verarbe
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Im Menü *Einrichtung » Märkte » Amazon » Berichte » Verarbeitung* erhältst du einen Überblick über den Verarbeitungsstand deiner Amazon-Berichte. Hier kannst du sehen, welche Berichte bereits verarbe
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbe
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.CompoundNumbers] Verwende in Komposita Ziffern statt Zahlwörter, um eine einheitliche Schreibweise sicherzustellen.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbe
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbe
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbe
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsExceptions] Kennzeichne Ausnahmen explizit und vermeide Wörter wie 'unter Umständen', damit die Aussage eindeutig ist.

2022-09-02 11:54 UTC, plenty-cicd-3 commented on docs/de-de/modules/maerkte/pages/amazon-einrichten.adoc
> +Achte jedoch darauf, dass die Leistungsfähigkeit deines Systems beeinträchtigt wird, wenn du zu viele oder zu große Berichte zurücksetzt. Neue Berichte werden dann unter Umständen erst später verarbe
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsTemporal] Vermeide Wörter, die die zeitliche Abfolge beschreiben, wie 'erst'. Dadurch wird die Verständlichkeit erhöht.

2022-09-02 11:57 UTC, merged