change pos menu paths
plentymarkets/plenty-manual-docs pull request #1108
Opened 2022-09-14 13:16 UTC by wdeister

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceNumberOfCommas] Schreibe den Satz so um, dass du weniger Kommas benötigst. Vermeide dabei Satzeinschübe und mehrere Nebensätze. Wenn der Bezug erhalten bleibt, kannst du einen Nebensatz an das Satzende stellen. Aufzählungen ab vier Elementen sollten in einer Liste dargestellt werden.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.OneToTwelveInDigits] Schreibe die Zahlen 1 bis 12 in Ziffern, um eine einheitliche Schreibweise sicherzustellen.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.OneToTwelveInDigits] Schreibe die Zahlen 1 bis 12 in Ziffern, um eine einheitliche Schreibweise sicherzustellen.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsCommonTerminology] Verwende 'erforderlich' statt 'notwendig', um eine einheitliche Terminologie sicherzustellen.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  Nachdem du Kassen gebucht hast, dauert es zunächst zwei bis drei Minuten, bis der Aktivierungsprozess im Hintergrund abgeschlossen ist. Logge dich dann aus deinem plentymarkets System aus und wieder
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  .Zahlungsart Barverkauf/EC-Karte
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidConnectingCharacters] Vermeide Sonderzeichen in Benennungen, um eine einheitliche Schreibweise sicherzustellen und die Lesbarkeit zu erhöhen.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
> +Stelle für die Zahlungsart *11 » Barverkauf/EC-Karte* außerdem im Menü *Einrichtung » POS » Mandant » [Mandant wählen\] » [POS wählen\] » Tab: Zahlungsart* die Option *Ohne Anbindung* im Bereich *EC-
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidConnectingCharacters] Vermeide Sonderzeichen in Benennungen, um eine einheitliche Schreibweise sicherzustellen und die Lesbarkeit zu erhöhen.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  → Das Tab *Grundeinstellungen* der Kasse wird geöffnet.
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceEndPunctuation] Jeder Satz muss mit einem Punkt, Doppelpunkt oder Fragezeichen abgeschlossen werden. Vermeide es, Sätze z.B. durch eine Liste zu unterbrechen. Dadurch werden Sinnzusammenhänge deutlich.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
>  → Das Tab *Grundeinstellungen* der Kasse wird geöffnet.
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.HeadingSubHeadingLength] Versuche maximal 3 Wörter in Zwischenüberschriften zu verwenden, um die Verständlichkeit und Übersichtlichkeit zu verbessern. Wenn das Thema z.B. bereits durch die Haupterüberschrift eindeutig benannt ist, muss derselbe Teil nicht in der Zwischenüberschrift wiederholt werden.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-online-bestellungen.adoc
>  . Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktiviere die Option, wenn der Warenausg
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-online-bestellungen.adoc
>  . Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktiviere die Option, wenn der Warenausg
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-online-bestellungen.adoc
>  . Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktiviere die Option, wenn der Warenausg
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.ConditionalOrder] Formuliere den Satz so um, dass die Bedingung am Anfang steht. Dadurch können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-online-bestellungen.adoc
>  . Die Option *Externer Auftrag: Warenausgang automatisch buchen* ist vorausgewählt. Der Warenausgang wird also nach der Bezahlung immer automatisch gebucht. Deaktiviere die Option, wenn der Warenausg
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordOrder] Formuliere den Satz so um, dass das Ziel der Handlung am Anfang steht. Dadurch wird die Verständlichkeit erhöht. Außerdem können Leser:innen entscheiden, ob sie die Handlung ausführen möchten, bevor sie die Handlungsanweisung selbst verarbeiten.

2022-09-14 13:17 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-rechtssicherheit.adoc
> +Im Menü *Einrichtung » POS » Mandant » [Mandant wählen\] » [POS wählen\]* wird im Tab *Grundeinstellungen* im Bereich *Fiskalisierung (Deutschland)* die *Seriennummer der TSE* und der *Public Key* de
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsMeaninglessPhrases] Vermeide Floskeln wie 'Bei Bedarf', damit die Aussage verbindlich ist.

2022-09-14 14:01 UTC, awinzek requested changes

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/integrating-plentymarkets-pos.adoc
> +. Go to *Setup » POS » [Select client]*.
```suggestion
. Go to *Setup » POS » [Select client\]*.
```

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/integrating-plentymarkets-pos.adoc
> +. Go to *Setup » POS » [Select client]*.
```suggestion
. Go to *Setup » POS » [Select client\]*.
```

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/integrating-plentymarkets-pos.adoc
> +. Go to *Setup » POS » [Select client]*.
```suggestion
. Go to *Setup » POS » [Select client\]*.
```

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/pos-legal-compliance.adoc
> +In the *Basic settings* tab of the *Setup » POS » [Select client]* menu, the *TSE serial number* and the *Public key* of the TSE unit are automatically entered and saved in the *Fiscalisation (German
```suggestion
In the *Basic settings* tab of the *Setup » POS » [Select client\]* menu, the *TSE serial number* and the *Public key* of the TSE unit are automatically entered and saved in the *Fiscalisation (Germany)* area. If needed, you can view and check the data there. If you want to set up a receipt printer manufactured by Epson, pay attention to our <<#550, tips>>.
```

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/pos-legal-compliance.adoc
> +* The POS identification number of the plentyPOS. Go to **Setup » POS » [Select client] » Open POS » Tab: Basic settings** to find the **POS identification number**.
```suggestion
* The POS identification number of the plentyPOS. Go to *Setup » POS » [Select client] » Open POS » Tab: Basic settings* to find the *POS identification number*.
```

2022-09-14 14:01 UTC, awinzek commented on docs/en-gb/modules/pos/pages/pos-online-orders.adoc
> +. Go to *Setup » POS » [Select client]*.
```suggestion
. Go to *Setup » POS » [Select client\]*.
```

2022-09-15 08:08 UTC, wdeister commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
> +Stelle für die Zahlungsart *11 » Barverkauf/EC-Karte* außerdem im Menü *Einrichtung » POS » Mandant » [Mandant wählen\] » [POS wählen\] » Tab: Zahlungsart* die Option *Ohne Anbindung* im Bereich *EC-
Damit wäre die Anweisung [POS wählen\] gelöscht.

2022-09-15 08:08 UTC, wdeister commented on docs/de-de/modules/pos/pages/pos-online-bestellungen.adoc
> +. Öffne das Menü *Einrichtung » POS » Mandant » [Mandant wählen\] » [POS wählen\]*.
Damit wäre die Anweisung [POS wählen\] gelöscht.

2022-09-15 08:09 UTC, wdeister commented on docs/de-de/modules/pos/pages/pos-rechtssicherheit.adoc
> +Im Menü *Einrichtung » POS » Mandant » [Mandant wählen\] » [POS wählen\]* wird im Tab *Grundeinstellungen* im Bereich *Fiskalisierung (Deutschland)* die *Seriennummer der TSE* und der *Public Key* de
Damit wäre die Anweisung [POS wählen\] gelöscht.

2022-09-15 08:11 UTC, wdeister commented on docs/en-gb/modules/pos/pages/integrating-plentymarkets-pos.adoc
> +For the payment method *11 » Cash sale/cash card*, also go to *Setup » POS » [Select client] » [Open POS] » Tab: Payment method* and select *Unconnected device* in the *POS terminal* area.
This sugggestion is invalid because no changes were made to the code.

2022-09-15 10:07 UTC, awinzek commented on docs/en-gb/modules/pos/pages/pos-legal-compliance.adoc
> +In the *Basic settings* tab of the *Setup » POS » [Select client\]* menu, the *TSE serial number* and the *Public key* of the TSE unit are automatically entered and saved in the *Fiscalisation (Germa
```suggestion
In the *Basic settings* tab of the *Setup » POS » [Select client\] » [Select POS\]* menu, the *TSE serial number* and the *Public key* of the TSE unit are automatically entered and saved in the *Fiscalisation (Germany)* area. If needed, you can view and check the data there. If you want to set up a receipt printer manufactured by Epson, pay attention to our <<#550, tips>>.
```

2022-09-15 10:36 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-einrichten.adoc
> +Stelle für die Zahlungsart *11 » Barverkauf/EC-Karte* außerdem im Menü *Einrichtung » POS » [Mandant wählen\] » [POS wählen\] » Tab: Zahlungsart* die Option *Ohne Anbindung* im Bereich *EC-Terminal*
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.AvoidConnectingCharacters] Vermeide Sonderzeichen in Benennungen, um eine einheitliche Schreibweise sicherzustellen und die Lesbarkeit zu erhöhen.

2022-09-15 10:36 UTC, plenty-cicd-3 commented on docs/de-de/modules/pos/pages/pos-rechtssicherheit.adoc
> +Im Menü *Einrichtung » POS » [Mandant wählen\] » [POS wählen\]* wird im Tab *Grundeinstellungen* im Bereich *Fiskalisierung (Deutschland)* die *Seriennummer der TSE* und der *Public Key* der TSE nach
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsMeaninglessPhrases] Vermeide Floskeln wie 'Bei Bedarf', damit die Aussage verbindlich ist.

2022-09-15 10:43 UTC, awinzek approved these changes

2022-09-15 10:44 UTC, merged