added description for GitLab tokens
plentymarkets/plenty-manual-docs pull request #1521
Opened 2022-11-30 15:08 UTC by thorbenbeuerbach

2022-11-30 15:09 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +Aktuell werden die drei im folgenden genannten Anbieter unterstützt. Möglicherweise kannst Du auch andere Anbieter verwenden.
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.OneToTwelveInDigits] Schreibe die Zahlen 1 bis 12 in Ziffern, um eine einheitliche Schreibweise sicherzustellen.

2022-11-30 15:09 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +Aktuell werden die drei im folgenden genannten Anbieter unterstützt. Möglicherweise kannst Du auch andere Anbieter verwenden.
⚠️ **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.WordsVague] Verwende verbindliche Formulierungen und vermeide Wörter wie 'Möglicherweise'.

2022-11-30 15:09 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +GitLab::
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceEndPunctuation] Jeder Satz muss mit einem Punkt, Doppelpunkt oder Fragezeichen abgeschlossen werden. Vermeide es, Sätze z.B. durch eine Liste zu unterbrechen. Dadurch werden Sinnzusammenhänge deutlich.

2022-11-30 15:09 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +GitLab::
🚫 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceEndPunctuation] Jeder Satz muss mit einem Punkt, Doppelpunkt oder Fragezeichen abgeschlossen werden. Vermeide es, Sätze z.B. durch eine Liste zu unterbrechen. Dadurch werden Sinnzusammenhänge deutlich.

2022-11-30 15:09 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach dem
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-12-01 08:33 UTC, ksted requested changes
For reference regarding the labels:
https://conventionalcomments.org/

2022-12-01 08:33 UTC, ksted commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +Aktuell werden die drei im folgenden genannten Anbieter unterstützt. Möglicherweise kannst Du auch andere Anbieter verwenden.
```suggestion
Aktuell werden folgende Anbieter unterstützt: GitHub, Bitbucket, GitLab. 
```
**suggestion (blocking):** By listing the providers right away, the user doesn't have to jump to the next section and back again.

2022-12-01 08:33 UTC, ksted commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +Hierfür können wir Dir aber keinen Support leisten.
```suggestion
Wenn du ein Plugin über einen anderen Anbieter hinzufügst, leisten wir bei Fehlverhalten keinen Support. 
```
**todo:** We don't capitalise the first letter when addressing the user.

**suggestion (non-blocking):** The rest of the suggestion removes some ambiguity. We haven't checked all possible providers, so in some cases we might be able to provide support. Even those cases would still be out of scope, though.

2022-12-01 08:33 UTC, ksted commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +. Benenne das Token und füge optional ein Ablaufdatum hinzu.
```suggestion
. Gib dem Token einen Namen. +
*_Optional:_* Gib ein Ablaufdatum ein.
```
**suggestion (non-blocking):** Clearly separates the required and optional parts to avoid ambiguity.

**nitpick:** "einen Namen geben" is more in line with the wording in the rest of the module than "benennen" I think.

2022-12-01 08:33 UTC, ksted commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach dem
```suggestion
→ Es wird ein neuer Token erzeugt. Der Token wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach dem Hinzufügen des Repositorys zu plentymarkets wieder löschen.
```
**suggestion (non-blocking):** Implements the bot's suggestion to avoid ambiguity. This is probably a problem in the GitLab and Bitbucket files, too, but we can address those separately at a later time.

2022-12-01 08:33 UTC, ksted commented on docs/en-gb/modules/plugins/pages/adding-plugins-system.adoc
> +We are not able to support other providers than the three mentioned below.
```suggestion
At the moment, we support the following providers: GitHub, Bitbucket, GitLab.

If you add plugins via a different provider, we won't provide any support in cases of unexpected behaviour.
```
See the German comment for details.

2022-12-01 08:45 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/chapter-git-plugins.adoc
> +Aktuell werden folgende Anbieter unterstützt: GitHub, Bitbucket, GitLab.
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.SentenceNumberOfCommas] Schreibe den Satz so um, dass du weniger Kommas benötigst. Vermeide dabei Satzeinschübe und mehrere Nebensätze. Wenn der Bezug erhalten bleibt, kannst du einen Nebensatz an das Satzende stellen. Aufzählungen ab vier Elementen sollten in einer Liste dargestellt werden.

2022-12-01 08:45 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +→ Es wird ein neuer Token erzeugt. Dieser wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach dem
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-12-01 08:45 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +→ Es wird ein neuer Token erzeugt. Der Token wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach d
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-12-01 08:45 UTC, plenty-cicd-3 commented on docs/de-de/modules/plugins/partials/git-zugriffstoken-gitlab.adoc
> +→ Es wird ein neuer Token erzeugt. Der Token wird im nächsten Schritt benötigt, lass die Seite also geöffnet oder speichere den Token lokal. Wenn du den Token lokal speicherst, solltest du ihn nach d
📝 **[vale]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[manual-docs-de.DeterminersDE] Verwende eindeutige pronominale Bezüge, um die Verständlichkeit des Texts zu erhöhen.

2022-12-01 09:00 UTC, ksted approved these changes

2022-12-01 09:33 UTC, merged