change: user account and access page
plentymarkets/plenty-manual-docs pull request #2003
Opened 2023-02-27 14:03 UTC by plentyofDennis

Changes in almost every chapter besides chapter 3.

Added more information about the simple and advanced mode.
Changed the paths of how to get to roles/security/accounts.
Changed instructions based on new UI.
Moved some chapters/ subchapters for more consistency.
Deleted parts that only regarded user rights (not role rights) and aren't part of the UI anymore.

2023-02-27 14:14 UTC, awinzek commented on docs/de-de/modules/_includes/partials/rights.adoc
> +. Gib der Rolle einen Namen
```suggestion
. Gib der Rolle einen Namen.
```

2023-02-27 14:15 UTC, khoffmeister commented on docs/de-de/modules/_includes/partials/rights.adoc
> +. Gib der Rolle einen Namen
```suggestion
. Gib der Rolle einen Namen.
```

2023-02-27 14:16 UTC, khoffmeister commented on docs/de-de/modules/_includes/partials/rights.adoc
> +→ Die Übersicht der Rollen öffnet sich.
```suggestion
→ Die Übersicht der Rollen wird angezeigt.
```

2023-02-27 14:18 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +* Mit Rollen gruppierst du Benutzer:innen-Konten und ordnest dieselben Berechtigungen zu mehreren Benutzer:innen-Konten.
```suggestion
* Mit Rollen gruppierst du Benutzer:innen-Konten und ordnest mehreren Konten dieselben Berechtigungen zu.
```

2023-02-27 14:18 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
>  . Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<tabelle-sicherheit-einstellen>>.
```suggestion
. Nimm die Einstellungen vor. Beachte dazu die Erläuterungen in <<#tabelle-sicherheit-einstellen>>.
```

2023-02-27 14:21 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Wenn diese Funktion nicht gewünscht ist, lass den Regler bei Null stehen.
```suggestion
Wenn diese Funktion nicht gewünscht ist, lasse den Regler bei 0 stehen.
```

2023-02-27 14:22 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Nimm Änderungen und Einstellungen gemäß <<tabelle-benutzer:innen-daten>> vor.
```suggestion
. Nimm Änderungen und Einstellungen gemäß <<#tabelle-benutzer:innen-daten>> vor.
```

2023-02-27 14:24 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Ob und in welchen Bereichen das Benutzer:innen-Konto als Eigner verfügbar sein soll, wird über bestimmte Berechtigungen im erweiterten Modus der Rollen bestimmt. Wenn du zum Beispiel eine Rolle erste
```suggestion
Ob und in welchen Bereichen das Benutzer:innen-Konto als Eigner verfügbar sein soll, wird über bestimmte Berechtigungen im erweiterten Modus der Rollen bestimmt. Wenn du zum Beispiel eine Rolle erstellst, die Eignerrechte für den Wareneingang haben soll, musst du im erweiterten Modus *Warenbestände* oder gezielter *Warenbestände » Wareneingänge* als Berechtigung freigeben. Welche Berechtigungen welche Eignerrechte aktiviert, findest du unter <<#tabelle-eignerrechte>>. Wenn das Benutzer:innenkonto über Adminrechte verfügt, verfügt es auch über alle Eignerrechte.
```

2023-02-27 14:27 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +|IP-Adresse des Rechners der Person des Benutzer:innen-Kontos eingeben, damit sich die Person mit diesem Benutzer:innen-Konto nur über diese IP-Adresse in das plentymarkets System einloggt.
```suggestion
|IP-Adresse des Rechners der Person des Benutzer:innen-Kontos eingeben, damit sich die Person mit diesem Benutzer:innen-Konto nur über diese IP-Adresse in das plentymarkets System einloggen kann.
```

2023-02-27 14:30 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +|Benutzer:innen-Zugang des Benutzer:innen-Kontos wählen. Es stehen die Zugänge *Administrator*, und *Nur API-Benutzer* zur Verfügung.
Hier würde ich noch mal wiederholen, was die Zugänge für Auswirkungen haben. Vor allem Administrator sollte ja nicht leichtfertig vergeben werden.

2023-02-27 14:31 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter dem plenty p und deinem Profilbild findest du die *persönlichen Einstellungen*. Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzer:innen-Konto gelten. Deshalb ist
```suggestion
Unter dem plentymarkets Logo oben links und deinem Profilbild oben rechts findest du die *persönlichen Einstellungen*. Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzer:innen-Konto gelten. Deshalb ist das Tab für dich auch nur in deinem eigenen Benutzer:innen-Konto sichtbar. Die persönlichen Einstellungen unterteilen sich in die Tabs xref:willkommen:system-personalisieren.adoc#70[Allgemein], und xref:willkommen:system-personalisieren.adoc#80[Shortcuts] die nur dich persönlich betreffen.
```

2023-02-27 14:31 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +| Text, der deinen Nachrichten und Kommentaren im Ticketsystem automatisch als Signatur angefügt wird.
```suggestion
| Text, der Nachrichten und Kommentaren dieser Benutzer:in im Ticketsystem automatisch als Signatur angefügt wird.
```

2023-02-27 14:33 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +| *Mail senden*
Kann das bitte in der UI umbenannt werden in "E-Mail senden"?

2023-02-27 14:33 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
>  . Wähle die zu bearbeitenden Benutzer:innen.
```suggestion
. Wähle (material:check_box[role=skyBlue]) die zu bearbeitenden Benutzer:innen.
```

2023-02-27 14:33 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Ob und in welchen Bereichen das Benutzer:innen-Konto als Eigner verfügbar sein soll, wird über bestimmte Berechtigungen im erweiterten Modus der Rollen bestimmt. Wenn du zum Beispiel eine Rolle erste
```suggestion
Ob und in welchen Bereichen das Benutzer:innen-Konto als Eigner verfügbar sein soll, wird über bestimmte Berechtigungen im erweiterten Modus der Rollen bestimmt. Wenn du zum Beispiel eine Rolle erstellst, die über Eigner-Rechte für den Wareneingang verfügen soll, musst du im erweiterten Modus *Warenbestände* oder gezielter *Warenbestände » Wareneingänge* als Berechtigung freigeben. Welche Berechtigungen welche Eignerrechte aktivieren findest du in <<tabelle-eignerrechte>>. Wenn das Benutzer:innenkonto über Adminrechte verfügt, verfügt es auch über alle Eignerrechte.
```

2023-02-27 14:34 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wechsel auf den erweiterten Modus (material:toggle_on[]).
```suggestion
. Wechsel in den erweiterten Modus (material:toggle_on[]).
```

2023-02-27 14:34 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
>  . Klicke auf *Gruppenfunktion*. +
Das passende Icon ist dann material:more_vert[].

2023-02-27 14:36 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter dem plenty p und deinem Profilbild findest du die *persönlichen Einstellungen*. Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzer:innen-Konto gelten. Deshalb ist
```suggestion
Unter dem plentymarkets p und deinem Profilbild findest du die *persönlichen Einstellungen*. Hier nimmst du Einstellungen vor, die nur für das im System angemeldete Benutzer:innen-Konto gelten. Deshalb ist das Tab für dich auch nur in deinem eigenen Benutzer:innen-Konto sichtbar. Die persönlichen Einstellungen unterteilen sich in die Tabs xref:willkommen:system-personalisieren.adoc#70[Allgemein], und xref:willkommen:system-personalisieren.adoc#80[Shortcuts] die nur dich persönlich betreffen.
```

2023-02-27 14:39 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Beim Erstellen und Bearbeiten von Rollen gibt es zwei Modi, den einfachen und den erweiterten. Welcher Modus für welche Rolle relevant ist, kommt auf die Rechte an, die der Rolle zugewiesen werden so
```suggestion
Beim Erstellen und Bearbeiten von Rollen gibt es zwei Modi: den einfachen Modus und den erweiterten Modus. Welcher Modus für welche Rolle relevant ist, kommt auf die Rechte an, die der Rolle zugewiesen werden sollen. Der einfache Modus und der erweiterte Modus sind verknüpft. Wenn du also Menü-Sichtbarkeiten im einfachen Modus auswählst, werden automatisch Berechtigungen im erweiterten Modus automatisch aktiv sein. Diese Verknüpfung existiert allerdings nur in diese Richtung: Wenn du also im erweiterten Modus Berechtigungen vergibst, werden keine Menü- oder Plugin-Sichtbarkeiten automatisch aktiv sein.
```

2023-02-27 14:39 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +**Einfacher Modus** = Im einfachen Modus kannst du die Sichtbarkeiten für Menüs und Plug-Ins vergeben. Die Tabelle des einfachen Modus ist genauso aufgebaut wie die Navigation und bildet zudem indivi
```suggestion
**Einfacher Modus** = Im einfachen Modus kannst du die Sichtbarkeiten für Menüs und Plugins vergeben. Die Tabelle des einfachen Modus ist genauso aufgebaut wie die Navigation und bildet zudem individuelle Plugins ab.
```

2023-02-27 14:40 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wähle im Reiter *Rechte* das Dropdown-Menü *Zugewiesene Rollen*
```suggestion
. Klicke im Bereich *Rechte* auf die Dropdown-Liste *Zugewiesene Rollen*.
```

2023-02-27 14:41 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +→ Das Dropdown-Menü klappt aus.
```suggestion
→ Die Dropdown-Liste klappt aus.
```

2023-02-27 14:42 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +In der Rollen-Detailansicht können Admins im Tab *Rollendefinerte Ansichten* bestimmen, welche Ansichten Benutzer:innen einer Rolle sehen und verwenden dürfen. Am Anfang ist immer die Standardansicht
```suggestion
In der Rollen-Detailansicht können Admins im Tab *Rollendefinierte Ansichten* bestimmen, welche Ansichten Benutzer:innen einer Rolle sehen und verwenden dürfen. Am Anfang ist immer die Standardansicht vorausgewählt. Existiert eine weitere Ansicht, kann die Standardansicht für eine Rolle deaktiviert und Rechte für eine andere Ansicht können zugewiesen werden. Beachte, dass immer mindestens eine Ansicht ausgewählt sein muss.
```

2023-02-27 14:43 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wähle das Tab *Rollendefinierte Ansichten*. +
```suggestion
. Klicke auf den Bereich *Rollendefinierte Ansichten*. +
```

2023-02-27 14:43 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Die Tabelle der Benutzerrechte gliedert sich in vier Spalten in denen Rechte vergeben werden können durch das Anhaken einer Checkbox: *Betrachten*, *Bearbeiten*, *Erstellen*, *Löschen*. Zwei dieser v
```suggestion
Die Tabelle der Benutzerrechte gliedert sich in vier Spalten. In diesen Spalten kannst du Rechte vergeben, indem du die Optionen *Betrachten*, *Bearbeiten*, *Erstellen* oder *Löschen* aktivierst. Zwei dieser vier Optionen ändern im erweiterten Modus ihre Namen: Aus *Betrachten* wird *Lesen* und aus *Bearbeiten* wird *Aktualisieren*.
```

2023-02-27 14:44 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]* legst du fest, welche Bereiche und Einstellungen die Person mit der jeweiligen Rolle sehen kann, wenn die Person ein Menü öffnet. Be
```suggestion
Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle wählen]* legst du fest, welche Bereiche und Einstellungen die Person mit der jeweiligen Rolle sehen kann, wenn die Person ein Menü öffnet. Bei fehlender Berechtigung ist zum Beispiel ein Lager oder sind Aufträge in einem Status für diese Person nicht sichtbar.
```

2023-02-27 14:44 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wechsel auf *Erweitert* (material:toggle_on[]).
```suggestion
. Wechsele auf *Erweitert* (material:toggle_on[role=skyBlue]).
```

2023-02-27 14:45 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter dem Punkt *Mobile* im einfachen Modus der Rollenerstellung bzw. -bearbeitung legst du fest, welche Bereiche und Kennzahlen für die Rolle mit de in der plentymarkets App sichtbar sein sollen.
```suggestion
Unter dem Punkt *Mobile* im einfachen Modus der Rollenerstellung bzw. -bearbeitung legst du fest, welche Bereiche und Kennzahlen für die Rolle in der plentymarkets App sichtbar sein sollen.
```

2023-02-27 14:47 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Klicke auf *Neu*. +
```suggestion
. Klicke auf material:add[] *Neu*. +
```

2023-02-27 14:47 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Beim Erstellen und Bearbeiten von Rollen gibt es zwei Modi, den einfachen und den erweiterten. Welcher Modus für welche Rolle relevant ist, kommt auf die Rechte an, die der Rolle zugewiesen werden so
```suggestion
Beim Erstellen und Bearbeiten von Rollen gibt es zwei Modi: Den einfachen und den erweiterten Modus. Welcher Modus für welche Rolle relevant ist, kommt auf die Rechte an, die der Rolle zugewiesen werden sollen. Der einfache Modus und der erweiterte Modus sind miteinander verknüpft. Wenn du also Menü-Sichtbarkeiten im einfachen Modus aktivierst, sind diese Berechtigungen auch im erweiterten Modus automatisch aktiv. Diese Verknüpfung existiert allerdings nur in diese Richtung. Wenn du also im erweiterten Modus Berechtigungen vergibst, werden keine Menü- oder Plug-In-Sichtbarkeiten automatisch aktiviert.
```

2023-02-27 14:48 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +**Einfacher Modus** = Im einfachen Modus kannst du die Sichtbarkeiten für Menüs und Plug-Ins vergeben. Die Tabelle des einfachen Modus ist genauso aufgebaut wie die Navigation und bildet zudem indivi
```suggestion
**Einfacher Modus** = Im einfachen Modus kannst du die Sichtbarkeiten für Menüs und Plugins vergeben. Die Tabelle des einfachen Modus ist genauso aufgebaut wie die Navigation und bildet zudem individuelle Plugins ab.
```

2023-02-27 14:48 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +**Erweiterter Modus** = Im erweiterteten Modus vergibst du ausschließlich Berechtigungen.
Was ist der Unterschied zwischen Sichtbarkeiten und Berechtigungen?

2023-02-27 14:49 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wähle im Reiter *Rechte* das Dropdown-Menü *Zugewiesene Rollen*
```suggestion
. Wähle im Tab *Rechte* das Dropdown-Menü *Zugewiesene Rollen*.
```

2023-02-27 14:49 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Nachdem du eine Rolle erstellt hast, wird sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, so dass du die Rolle auch später wieder öffnen und bearbeiten kannst. Rollen werden in der
```suggestion
Nachdem du eine Rolle erstellt hast, wird sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, sodass du die Rolle auch später wieder öffnen und bearbeiten kannst. Rollen werden in der Übersicht nach ID gelistet. Jede Rolle gliedert sich in vier Bereiche. Im Bereich *Einstellungen* kannst du den Namen der Rolle ändern. Im Bereich *Rechte* ordnest du der Rolle im Einfachen Modus Menü-Sichtbarkeiten sowie Plugin-Sichtbarkeiten zu, im Erweiterten Modus die REST-API Berechtigungen. Im Bereich *Rollendefinierte Ansichten* kannst du die verfügbaren MyView-Ansichten für eine Rolle anpassen. Es ist automatisch immer die Standardansicht ausgewählt. Im Bereich *Zugrifssrechte* lassen sich die Ressourcen aktivieren, auf die eine Rolle Zugriff haben soll. Details zu den Berechtigungen findest du hier auf der Seite im Kapitel xref:business-entscheidungen:benutzerkonten-zugaenge.adoc#105[Rechte verwalten].
```

2023-02-27 14:49 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +→ Das Dropdown-Menü klappt aus.
```suggestion
→ Das Dropdown-Menü wird ausgeklappt.
```

2023-02-27 14:50 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Wähle eine vorhandene Rolle oder erstelle eine neue auf *Neue Rolle erstellen ...* (material:add[]).
```suggestion
. Wähle eine vorhandene Rolle. +
*_Oder:_* Erstelle eine neue Rolle. Klicke dazu auf *Neue Rolle erstellen ...* (material:add[]).
```

2023-02-27 14:50 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/partials/benutzerkonto-erstellen.adoc
> +. Klicke auf *Neu* (material:add[]). +
```suggestion
. Klicke auf material:add[] *Neu*. +
```

2023-02-27 14:51 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/partials/benutzerkonto-erstellen.adoc
>  → Das Fenster *Neuen Benutzer anlegen* wird geöffnet.
```suggestion

```

2023-02-27 14:52 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Im Menü *Einrichtung » Kontoverwaltung » Rollen* können neue Rollen erstellt werden oder existierende Rollen angepasst werden. Beim Erstellen oder Bearbeiten einer Rolle kann im Menüpunkt *Zugriffsbe
Das soll dann "Zugriffsrechte" heißen, oder?

2023-02-27 14:53 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Sobald du die Rolle an das Konto vergeben hast, erhält das Konto die dazugehörigen Rechte.
```suggestion
→ Das Konto erhält die Rechte der Rolle.
```

2023-02-27 14:53 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
>  → Das Fenster *Neue Rolle* wird geöffnet.
der Satz kann mMn komplette weg.

2023-02-27 14:58 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]* legst du fest, welche Bereiche und Einstellungen die Person mit der jeweiligen Rolle sehen kann, wenn die Person ein Menü öffnet. Be
```suggestion
Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]* legst du fest, welche Bereiche und Einstellungen Personen mit dieser Rolle sehen können, wenn sie ein Menü öffnen. Wenn die Rolle zum Beispiel keine Berechtigungen für ein Lager oder bestimmte Auftragsstatus hat, sind das Lager oder Aufträge in diesem Status für diese Person nicht sichtbar.
```

2023-02-27 14:59 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +.Tab *Berechtigung* eines Benutzer:innen-Kontos vom Typ Backend
Ich dachte den Typ Backend gibt es nicht mehr?

2023-02-27 15:02 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +|Auftragsstatus festlegen, die die Person mit diesem Benutzer:innen-Konto sehen darf.
```suggestion
|Auftragsstatus festlegen, die Personen mit dieser Rolle sehen dürfen.
```

2023-02-27 15:04 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +*Alle* = Die Person mit diesem Benutzer:innen-Konto hat Zugriff auf alle Lager. +
```suggestion
*Alle* = Personen mit dieser Rolle haben Zugriff auf alle Lager. +
```

2023-02-27 15:04 UTC, plentyofDennis commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Im Menü *Einrichtung » Kontoverwaltung » Rollen* können neue Rollen erstellt werden oder existierende Rollen angepasst werden. Beim Erstellen oder Bearbeiten einer Rolle kann im Menüpunkt *Zugriffsbe
Ja genau! Heißt es auch schon, hab das hier wohl überlesen

2023-02-27 15:05 UTC, fmutschler requested changes

2023-02-27 15:05 UTC, fmutschler commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +→ Der Einfache Modus mit den Rechten wird geöffnet.
Hier stolper ich ein bisschen drüber; I may be pedantic though.
Ist der einfach Modus dasjenige, was geöffnet wird? Oder wird nicht eher etwas anderes (Übersicht der Rechte/Rollen?) *im* einfachen Modus geöffnet?

2023-02-27 15:05 UTC, fmutschler commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Klicke auf material:search[], um alle Rollen zu sehen.
fehlt hier noch das keyword "Suchen"? In der nächsten Config weiter unten benutzt du das. Consistency.

2023-02-27 15:05 UTC, fmutschler commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter *Einrichtung » Kontoverwaltung » Rollen » [Rolle auswählen]* legst du fest, welche Bereiche und Einstellungen die Person mit der jeweiligen Rolle sehen kann, wenn die Person ein Menü öffnet. Be
Ich würde mich im letzten Satz für ein Beispiel entscheiden, dann fuckt das die Grammatik nicht so sehr ab :)

2023-02-27 15:07 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Unter dem Punkt *Mobile* im einfachen Modus der Rollenerstellung bzw. -bearbeitung legst du fest, welche Bereiche und Kennzahlen für die Rolle mit de in der plentymarkets App sichtbar sein sollen.
```suggestion
Unter dem Punkt *Mobile* im einfachen Modus der Rollen legst du fest, welche Bereiche und Kennzahlen für die Rolle in der plentymarkets App sichtbar sein sollen.
```

2023-02-27 15:08 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Rollen können von Benutzer:innen des Zugangs *Admin* erstellt werden oder von Nutzer:innen, die eine Rolle mit den notwendigen Rechten hat.
```suggestion
Rollen können von Benutzer:innen des Zugangs *Admin* erstellt werden oder von Nutzer:innen, die eine Rolle mit den notwendigen Rechten haben.
```

2023-02-27 15:10 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Nachdem du eine Rolle erstellt hast, wird sie zur Bearbeitung geöffnet und der Rollenübersicht hinzugefügt, so dass du die Rolle auch später wieder öffnen und bearbeiten kannst. Rollen werden in der
Das ist keine Beschreibung, wie man Rollen bearbeitet. Hier fehlt eine Schrittliste. Die allgemeinen Infos, was man alles anpassen kann, sind ja schon weiter oben beschrieben.

2023-02-27 15:11 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Rollen können von Benutzer:innen des Zugangs *Admin* erstellt werden oder von Nutzer:innen, die eine Rolle mit den notwendigen Rechten hat.
Diese Info könnte außerdem deutlich weiter oben kommen, denn hier hat man ja schon längst Rollen erstellt.

2023-02-27 15:11 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Klicke auf das Dropdown-Menü *Zugewiesene Rollen*
```suggestion
. Klicke auf das Dropdown-Menü *Zugewiesene Rollen*.
```

2023-02-27 15:13 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Filter helfen dir bei der Suche nach Benutzer:innen-Konten. Ohne Filter werden in der Übersicht alle Benutzer:innen-Konten angezeigt. Folgende Elemente und Funktionen sind im Menü *Konten* verfügbar.
```suggestion
Filter helfen dir bei der Suche nach Benutzer:innen-Konten. Ohne Filter werden in der Übersicht alle Benutzer:innen-Konten angezeigt.
```

2023-02-27 15:13 UTC, khoffmeister commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Klicke auf Suchen (icon:search[]).
```suggestion
. Klicke auf Suchen (icon:search[]). +
→ Die Ansicht wird gefiltert.
```

2023-02-27 15:29 UTC, fmutschler commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +. Vergib die Berechtigungen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzer
```suggestion
. Vergib die Berechtigungen in dem jeweiligen Bereich durch Anklicken der Checkboxen. Aktiviere komplette Bereiche oder klappe Bereiche auf, um einzelne Berechtigungen zu aktivieren, die dem Benutzer:innen-Konto zugewiesen werden sollen.
```

2023-02-27 15:29 UTC, fmutschler commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +→ Die Rolle wird kopiert und mit dem Namen *Kopie von bisheriger Rolle* erstellt .
Lautet der neue Name buchstäblich "Kopie von bisheriger Rolle"?
Oder ist es "Kopie von [NAME DER KOPIERTEN ROLLE]?

Falls ersichtlich ist was ich meine?

2023-02-27 15:30 UTC, plentyofDennis commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +In plentymarkets werden Rechte über Rollen an Benutzer:innen vergeben. Dies beinhaltet Menü- und Plugin-Sichtbarkeiten sowie REST-API-Berechtigungen. Ein:e Benutzer:in hat also immer die Rechte, die
Letzteres!

2023-02-27 15:36 UTC, plentyofDennis commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +.Tab *Berechtigung* eines Benutzer:innen-Kontos vom Typ Backend
Gibt es auch nicht, die Stelle ist mir durch die Lappen gegangen

2023-02-27 16:16 UTC, plentyofDennis commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +| *Mail senden*
Nehme das morgen mit ins Daily, denke das sollte kein Problem sein

2023-02-27 16:21 UTC, plentyofDennis commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +→ Der Einfache Modus mit den Rechten wird geöffnet.
Du hast schon Recht, ist die elegantere Lösung!

2023-02-27 16:46 UTC, fmutschler approved these changes

2023-02-28 11:00 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +In plentymarkets werden Rechte über Rollen an Benutzer:innen vergeben. Dies beinhaltet Menü- und Plugin-Sichtbarkeiten sowie REST-API-Berechtigungen. Ein:e Benutzer:in hat also immer die Rechte, die
```suggestion
In plentymarkets werden Rechte über Rollen an Benutzer:innen vergeben. Dies beinhaltet Menü- und Plugin-Sichtbarkeiten sowie REST-API-Berechtigungen. Ein:e Benutzer:in hat also immer die Rechte, die von der Rolle zugewiesen werden. Die einzige Ausnahme dabei bilden Administratoren, die unabhängig von ihrer Rolle alle Rechte im System besitzen.
```

2023-02-28 11:01 UTC, awinzek commented on docs/de-de/modules/business-entscheidungen/pages/benutzerkonten-zugaenge.adoc
> +Die Tabelle der Benutzerrechte gliedert sich in vier Spalten. In diesen Spalten kannst du Rechte vergeben, indem du die Optionen *Betrachten*, *Bearbeiten*, *Erstellen* oder *Löschen* aktivierst. Zwe
```suggestion
Die Tabelle der Benutzer:innenrechte gliedert sich in vier Spalten. In diesen Spalten kannst du Rechte vergeben, indem du die Optionen *Betrachten*, *Bearbeiten*, *Erstellen* oder *Löschen* aktivierst. Zwei dieser vier Optionen ändern im erweiterten Modus ihre Namen: Aus *Betrachten* wird *Lesen* und aus *Bearbeiten* wird *Aktualisieren*.
```

2023-03-02 06:45 UTC, merged